In [17]:
import torch
from IPython import display
from d2l import torch as d2l

batch_size = 256
train_iter, test_iter = d2l.load_data_fashion_mnist(batch_size)  # 在09-mnist中有实现

In [18]:
num_inputs = 784  # 28*28
num_outputs = 10

W = torch.normal(0, 0.01, size=(num_inputs, num_outputs), requires_grad=True)
b = torch.zeros(num_outputs, requires_grad=True)

In [19]:
X = torch.tensor([[1.0, 2.0 ,3.0],[4.0, 5.0, 6.0]])
X.sum(0, keepdim=True), X.sum(1, keepdim=True)

(tensor([[5., 7., 9.]]),
 tensor([[ 6.],
         [15.]]))

In [20]:
def softmax(X):
    X_exp = torch.exp(X)
    partition = X_exp.sum(1, keepdim=True)
    return X_exp/ partition  # 这里应用了广播机制

In [21]:
X = torch.normal(0, 1, (2, 5))
X_prob = softmax(X)
X_prob, X_prob.sum(1)

(tensor([[0.0852, 0.1678, 0.4828, 0.1840, 0.0802],
         [0.2275, 0.0985, 0.6055, 0.0328, 0.0357]]),
 tensor([1., 1.]))

In [23]:
def net(X):
    return softmax(torch.matmul(X.reshape((-1, W.shape[0])), W) +b)

In [24]:
y = torch.tensor([0, 2])
y_hat = torch.tensor([[0.1, 0.3, 0.6], [0.3, 0.2, 0.5]])
y_hat[[0, 1], y]  # [0,0] [1,2]

tensor([0.1000, 0.5000])

In [ ]:
def cross_entropy(y_hat, y):