# 读写文件
加载和保存张量

In [2]:
import torch
from torch import nn
from torch.nn import functional as F

x = torch.arange(4)
torch.save(x, 'x-file')

x2 = torch.load('x-file')
x2

tensor([0, 1, 2, 3])

存储一个张量列表，然后把它们读回内存

In [3]:
y = torch.zeros(4)
torch.save([x, y], 'x-files')
x2, y2 = torch.load('x-files')
(x2, y2)

(tensor([0, 1, 2, 3]), tensor([0., 0., 0., 0.]))

写入或读取从字符串映射到张量的字典

In [4]:
mydict = {'x': x, 'y': y}
torch.save(mydict, 'mydict')
mydict2 = torch.load('mydict')
mydict2

{'x': tensor([0, 1, 2, 3]), 'y': tensor([0., 0., 0., 0.])}

# 加载和保存模型参数

In [6]:
class MLP(nn.Module):
    def __init__(self):
        super().__init__()
        self.hidden = nn.Linear(20, 256)
        self.output = nn.Linear(256, 10)

    def forward(self, x):
        return self.output(F.relu(self.hidden(x)))

net = MLP()
X = torch.randn(size=(2, 20))
Y = net(X)

In [7]:
net.state_dict()

OrderedDict([('hidden.weight',
              tensor([[ 0.1328, -0.0106,  0.0247,  ..., -0.0915, -0.0072, -0.1126],
                      [ 0.0513,  0.1855, -0.0187,  ..., -0.1696,  0.0569, -0.0919],
                      [-0.1628, -0.0544,  0.0200,  ..., -0.2151, -0.1535,  0.1455],
                      ...,
                      [ 0.1156, -0.0784,  0.0283,  ...,  0.1045, -0.0789, -0.0448],
                      [ 0.1106,  0.1883,  0.0755,  ...,  0.1454, -0.0547,  0.0359],
                      [ 0.2050,  0.1042, -0.1148,  ...,  0.1685, -0.0512,  0.0396]])),
             ('hidden.bias',
              tensor([-0.1594,  0.1560, -0.2223, -0.1120,  0.1184,  0.1972, -0.0382, -0.1765,
                       0.0278, -0.1608, -0.0665, -0.1513,  0.1445,  0.1863,  0.1465, -0.1201,
                      -0.0047,  0.0922, -0.1336, -0.0307,  0.0591, -0.2057, -0.0770, -0.1135,
                      -0.1482, -0.1768, -0.1031, -0.0599, -0.1205,  0.1301,  0.2203, -0.0973,
                      -0.0070,

将模型的参数存储在一个叫做“mlp.params”的文件中

In [8]:
torch.save(net.state_dict(), 'mlp.params')

实例化了原始多层感知机模型的一个备份。 这里我们不需要随机初始化模型参数，而是直接读取文件中存储的参数

In [12]:
clone = MLP()
clone.load_state_dict(torch.load('mlp.params'))
clone.eval()

MLP(
  (hidden): Linear(in_features=20, out_features=256, bias=True)
  (output): Linear(in_features=256, out_features=10, bias=True)
)

In [13]:
Y_clone = clone(X)
Y_clone == Y

tensor([[True, True, True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True, True, True]])