# 自定义层
构造一个没有任何参数的自定义层

In [1]:
import torch
import torch.nn.functional as F
from torch import nn

class CenteredLayer(nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, X):
        return X - X.mean()  # 将均值变为0

layer = CenteredLayer()
layer(torch.FloatTensor([1,2,3,4,5]))

tensor([-2., -1.,  0.,  1.,  2.])

# 将层作为组件合并到更复杂的模型中。

In [2]:
net = nn.Sequential(nn.Linear(8, 128), CenteredLayer())

Y = net(torch.rand(4,8))
Y.mean()

tensor(4.6566e-09, grad_fn=<MeanBackward0>)

# 带参数的层
该层需要输入参数：in_units和units，分别表示输入数和输出数。

In [3]:
class MyLinear(nn.Module):
    def __init__(self, in_units, units):
        super().__init__()
        self.weight = nn.Parameter(torch.randn(in_units, units))
        self.bias = nn.Parameter(torch.randn(units,))

    def forward(self, X):
        linear = torch.matmul(X, self.weight.data) + self.bias.data
        return F.relu(linear)

dense = MyLinear(5, 3)
dense.weight

Parameter containing:
tensor([[-0.0175,  1.0527, -0.8559],
        [-0.0653, -1.4106,  0.0860],
        [-1.5653, -0.7121, -1.2524],
        [ 1.4651, -0.1142, -0.1704],
        [-0.0815, -2.4022, -0.7695]], requires_grad=True)

# 使用自定义层直接执行前向传播计算

In [5]:
dense(torch.rand(2,5))

tensor([[0.0000, 0.3726, 0.0000],
        [0.0000, 0.0000, 0.0000]])

# 使用自定义层构建模型

In [6]:
net = nn.Sequential(MyLinear(64, 8), MyLinear(8, 1))
net(torch.rand(2, 64))

tensor([[4.4741],
        [2.4175]])